"""Resource-aware test execution.

The suite's contention machinery: a machine-readable resource vocabulary
(``resources``), machine-global leases arbitrating exclusive use across
processes and sessions (``leases``), progress-based deadlines that fail on
death or stall rather than on elapsed wall clock (``progress``), run-status
polling built on them (``polling``), registry-backed service endpoint
resolution (``endpoints``), and the pytest plugin
(``plugin``) that derives scheduling groups, timeout backstops, and lease
acquisition from the declarations. The ACP test peer (``acp``) is the simulated
agent side of the protocol over stdio, with the frame builders and the request and
reply exchange a client-side test uses against it. Beside them sits the
real-process support every test tier composes rather than retypes: the gateway
boot and its peers (``boot``), the loopback listeners a test points code at
(``http``), the run-start verb shaped once (``verbs``) and the gateway verb kit
built around it (``gateway_verbs``), the acceptance harness that drives a
document-authoring run end to end (``acceptance``), the readers that check a
decoded JSON response's shape (``payloads``), the inputs a test chooses for a
production constructor (``factories``, ``catalog_authority``), and the in-process
fixture lanes a test gateway or test process holds (``lanes``). The control plane's
test peers sit with them: the production worker served in-process over a real
executor (``worker_app``), the run rows a test seats through the repositories
(``seeding``), and the runs it parks on a real interrupt (``parking``).

The plugin is loaded by the repository-root ``conftest.py``, which is the one
channel that neither an ``addopts`` override can strip nor a consumer
environment can inherit; importing this facade does not register it. Public
names resolve lazily so the contained runner can declare its test environment
before any test-only import reaches the eager settings singleton.

The facade re-exports each support module whole. The contained runner's own
modules (``plugin``, ``runner``, ``runner_child``, ``completion``) are the
exception: they run before or outside the test process and are named by module
path, as ``-m`` and ``pytest_plugins`` do.
"""

from importlib import import_module
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .acceptance import (
        CODER_ROLE,
        GATEWAY_AUTH_HEADERS,
        MODE_AUTONOMOUS,
        MODE_MANUAL,
        OBSERVE_DEADLINE_SECONDS,
        POLICY_AUTO,
        POLICY_HUMAN,
        PRESET_DETERMINISTIC,
        PRESET_LIVE,
        SOLO_CODER_PRESET,
        AcceptanceCase,
        AcceptanceHarness,
        Materialization,
        ResilientAuthoringClient,
        extract_bridge_tools,
        is_live_lane,
        message_content,
        mint_raw_token,
        observe_bridged_authoring_run,
        reachable_stack,
        resolve_selection,
        runtime_budget_for,
        snapshot_vault,
        vault_write_delta,
    )
    from .acp import (
        ACP_PROTOCOL_VERSION,
        ACP_SIMULATOR_PATH,
        REQUEST_PERMISSION_METHOD,
        acp_request,
        exchange_acp_request,
        initialize_request,
        initialize_result,
        read_acp_frame,
        request_permission_params,
        request_permission_request,
        simulator_command,
    )
    from .antigravity import antigravity_credential_path
    from .boot import (
        DEFAULT_ATTACH_CREDENTIAL,
        DEFAULT_OWNERSHIP_CAPABILITY,
        FIRST_DEMAND_TIMEOUT,
        FOREIGN_WORKER_PROGRAM,
        LOOPBACK_TIMEOUT,
        READINESS_TIMEOUT,
        BootedGateway,
        GatewayBootError,
        SignalledChild,
        WatchedProcess,
        adopted_spawner,
        armed_gateway_env,
        await_gateway_ready,
        await_ready,
        booted_gateway,
        broker_gateway_env,
        desktop_workspace,
        foreign_worker,
        gateway_process_env,
        gateway_script,
        log_tail,
        loopback_callback_bridge,
        read_worker_ipc_secret,
        reap_process,
        seat_app_home,
        spawn_gateway,
        spawn_logged,
        spawn_signalled,
        spawn_until_ready,
        worker_lifecycle_gateway_script,
    )
    from .catalog import (
        LIVE_PROVIDER_CATALOG_SELECTION_ENVIRON,
        LIVE_PROVIDER_OVERRIDE_SELECTION_ENVIRON,
        LIVE_PROVIDER_PREREQUISITES,
        NoSelectableLaneError,
        async_catalog_run_fields,
        async_fetch_in_process_selection,
        async_fetch_provider_catalog,
        catalog_run_fields,
        declared_lane_model_value,
        fetch_in_process_selection,
        fetch_in_process_selection_at,
        fetch_provider_catalog,
        in_process_lane_required,
        in_process_lane_selection,
        in_process_selection,
        is_selectable,
        live_provider_catalog_selector_is_configured,
        live_provider_override_selector_is_configured,
        named_lane_selection,
        override_selection_from_served_catalog,
        selection_from_served_catalog,
        unvalidated_selection,
    )
    from .catalog_authority import current_execution_metadata
    from .children import (
        DEFAULT_IDLE_WINDOW_S,
        await_child,
        child_tree_progress,
        file_size_fingerprint,
        measured_child_startup_s,
        run_child,
    )
    from .cli import (
        clean_subprocess_environment,
        combined_output,
        inherited_environment,
        run_cli,
    )
    from .endpoints import ResolvedService, resolve_gateway_url, resolve_service
    from .environment import (
        armed_desktop_app_home,
        armed_environment,
        settings_override,
    )
    from .factories import LaneInventoryFactory, build_settings, load_settings
    from .gateway_verbs import (
        DEFAULT_ATTACH_AUTHORIZATION,
        DEFAULT_REQUIRED_ROLE,
        DEFAULT_TEAM_PRESET,
        GatewayVerbs,
        async_run_start_body,
        gateway_run_verbs,
        role_tokens,
    )
    from .graph import (
        add_test_node,
        ainvoke_test_graph,
        compile_test_graph,
        new_state_graph,
        stand_in_definition_digest,
    )
    from .harness_names import (
        COMPLETION_ENDPOINT_ENV,
        COMPLETION_OWNER_PID_ENV,
        CPU_BUDGET_ENV,
        TEST_ENV_PREFIX,
    )
    from .http import (
        JsonReplyHandler,
        health_listener,
        loopback_uvicorn,
        serve_handler,
        serve_on_loopback,
        serve_on_loopback_in_thread,
        uvicorn_started,
    )
    from .lanes import (
        DETERMINISTIC_LANE,
        LANES,
        armed_lane_environment,
        deterministic_model_assignment,
        frozen_deterministic_selection,
        held_turns,
        register_lanes,
        seated_lanes,
    )
    from .lanes.deterministic import UNATTENDED_REPLY, DeterministicResearchAdrChatModel
    from .leases import (
        LEASE_TTL_MS,
        Lease,
        LeaseAcquisitionTimeoutError,
        hold_lease,
        lease_home,
        live_shared_holder_count,
    )
    from .links import plant_link_to_file
    from .markers import LayerRule, apply_layer_markers
    from .parking import (
        ClarificationGraph,
        ParkedClarification,
        clarification_graph,
        park_clarification,
        park_document_approval,
        park_journaled_permission,
        park_journaled_permissions,
        park_permission,
        park_permissions,
        park_plan_approval,
    )
    from .payloads import (
        json_list,
        json_object,
        json_object_list,
        json_text,
        required_bool,
        required_text,
        text_list,
    )
    from .polling import (
        is_terminal,
        ok_body,
        wait_for_run_status,
        wait_for_run_status_async,
    )
    from .ports import (
        SCRATCH_ROLE,
        PortAllocationError,
        allocate_free_ports,
        free_port,
        hold_for_process_lifetime,
        reserve_scratch_ports,
    )
    from .progress import (
        LivenessWatch,
        ProgressDeadline,
        ProgressStalledError,
        ResourceDiedError,
        registry_watch,
        wait_for,
        wait_for_async,
    )
    from .purity import (
        IMPURE_FIXTURES,
        SERVICE_MARKER,
        forfeits_purity,
        uses_impure_fixture,
    )
    from .resources import (
        MARKER_NAME,
        RESOURCES,
        SCRATCH_PREFIX,
        ResourceClaim,
        ResourceDeclarationError,
        ResourceSpec,
        declared_claims,
        exclusive_keys,
        resolve_spec,
    )
    from .seeding import (
        elect_status,
        record_completed_checkpoint,
        seed_accepted_thread,
        seed_completed_authority,
        seed_create_action,
        seed_journaled_thread,
        seed_live_thread,
        seed_thread_expectation,
    )
    from .session_root import (
        TEST_ROOT_NAME,
        TestSessionSettings,
        prune_stale_dirs,
        seat_test_session,
        session_scratch_dir,
    )
    from .sessions import (
        SESSION_LEASE_KEY,
        effective_worker_count,
        live_peer_sessions,
        machine_cpu_budget,
        register_session,
    )
    from .sse import SseFrame, SseReader, decode_frame, read_frame, read_frames_until
    from .verbs import (
        RunVerbs,
        actor_tokens_body,
        status_and_json,
    )
    from .worker_app import ServedWorker, capacity_holders, served_worker


#: Fully-qualified (never relative) submodule names: this dict's string values
#: are themselves how a repository-configured surface names a shipped module by
#: dotted string rather than by import (see ``string_module_edges`` in
#: ``dev/audit/unreachable_code.py``), the same mechanism that keeps a uvicorn
#: factory or a worker process target live. A relative ``".children"`` here
#: would resolve identically at import time but would not be recognised as
#: naming ``vaultspec_a2a.testing.children``, leaving every submodule this
#: facade lazily loads misreported as reachable only through type checking.
_LAZY_EXPORTS = {
    "CODER_ROLE": ("vaultspec_a2a.testing.acceptance", "CODER_ROLE"),
    "GATEWAY_AUTH_HEADERS": (
        "vaultspec_a2a.testing.acceptance",
        "GATEWAY_AUTH_HEADERS",
    ),
    "MODE_AUTONOMOUS": ("vaultspec_a2a.testing.acceptance", "MODE_AUTONOMOUS"),
    "MODE_MANUAL": ("vaultspec_a2a.testing.acceptance", "MODE_MANUAL"),
    "OBSERVE_DEADLINE_SECONDS": (
        "vaultspec_a2a.testing.acceptance",
        "OBSERVE_DEADLINE_SECONDS",
    ),
    "POLICY_AUTO": ("vaultspec_a2a.testing.acceptance", "POLICY_AUTO"),
    "POLICY_HUMAN": ("vaultspec_a2a.testing.acceptance", "POLICY_HUMAN"),
    "PRESET_DETERMINISTIC": (
        "vaultspec_a2a.testing.acceptance",
        "PRESET_DETERMINISTIC",
    ),
    "PRESET_LIVE": ("vaultspec_a2a.testing.acceptance", "PRESET_LIVE"),
    "SOLO_CODER_PRESET": ("vaultspec_a2a.testing.acceptance", "SOLO_CODER_PRESET"),
    "AcceptanceCase": ("vaultspec_a2a.testing.acceptance", "AcceptanceCase"),
    "AcceptanceHarness": ("vaultspec_a2a.testing.acceptance", "AcceptanceHarness"),
    "Materialization": ("vaultspec_a2a.testing.acceptance", "Materialization"),
    "ResilientAuthoringClient": (
        "vaultspec_a2a.testing.acceptance",
        "ResilientAuthoringClient",
    ),
    "extract_bridge_tools": (
        "vaultspec_a2a.testing.acceptance",
        "extract_bridge_tools",
    ),
    "is_live_lane": ("vaultspec_a2a.testing.acceptance", "is_live_lane"),
    "message_content": ("vaultspec_a2a.testing.acceptance", "message_content"),
    "mint_raw_token": ("vaultspec_a2a.testing.acceptance", "mint_raw_token"),
    "observe_bridged_authoring_run": (
        "vaultspec_a2a.testing.acceptance",
        "observe_bridged_authoring_run",
    ),
    "reachable_stack": ("vaultspec_a2a.testing.acceptance", "reachable_stack"),
    "resolve_selection": ("vaultspec_a2a.testing.acceptance", "resolve_selection"),
    "runtime_budget_for": ("vaultspec_a2a.testing.acceptance", "runtime_budget_for"),
    "snapshot_vault": ("vaultspec_a2a.testing.acceptance", "snapshot_vault"),
    "vault_write_delta": ("vaultspec_a2a.testing.acceptance", "vault_write_delta"),
    "ACP_PROTOCOL_VERSION": ("vaultspec_a2a.testing.acp", "ACP_PROTOCOL_VERSION"),
    "ACP_SIMULATOR_PATH": ("vaultspec_a2a.testing.acp", "ACP_SIMULATOR_PATH"),
    "REQUEST_PERMISSION_METHOD": (
        "vaultspec_a2a.testing.acp",
        "REQUEST_PERMISSION_METHOD",
    ),
    "acp_request": ("vaultspec_a2a.testing.acp", "acp_request"),
    "exchange_acp_request": ("vaultspec_a2a.testing.acp", "exchange_acp_request"),
    "initialize_request": ("vaultspec_a2a.testing.acp", "initialize_request"),
    "initialize_result": ("vaultspec_a2a.testing.acp", "initialize_result"),
    "read_acp_frame": ("vaultspec_a2a.testing.acp", "read_acp_frame"),
    "request_permission_params": (
        "vaultspec_a2a.testing.acp",
        "request_permission_params",
    ),
    "request_permission_request": (
        "vaultspec_a2a.testing.acp",
        "request_permission_request",
    ),
    "simulator_command": ("vaultspec_a2a.testing.acp", "simulator_command"),
    "antigravity_credential_path": (
        "vaultspec_a2a.testing.antigravity",
        "antigravity_credential_path",
    ),
    "DEFAULT_ATTACH_CREDENTIAL": (
        "vaultspec_a2a.testing.boot",
        "DEFAULT_ATTACH_CREDENTIAL",
    ),
    "DEFAULT_OWNERSHIP_CAPABILITY": (
        "vaultspec_a2a.testing.boot",
        "DEFAULT_OWNERSHIP_CAPABILITY",
    ),
    "FIRST_DEMAND_TIMEOUT": ("vaultspec_a2a.testing.boot", "FIRST_DEMAND_TIMEOUT"),
    "FOREIGN_WORKER_PROGRAM": ("vaultspec_a2a.testing.boot", "FOREIGN_WORKER_PROGRAM"),
    "LOOPBACK_TIMEOUT": ("vaultspec_a2a.testing.boot", "LOOPBACK_TIMEOUT"),
    "READINESS_TIMEOUT": ("vaultspec_a2a.testing.boot", "READINESS_TIMEOUT"),
    "BootedGateway": ("vaultspec_a2a.testing.boot", "BootedGateway"),
    "GatewayBootError": ("vaultspec_a2a.testing.boot", "GatewayBootError"),
    "SignalledChild": ("vaultspec_a2a.testing.boot", "SignalledChild"),
    "WatchedProcess": ("vaultspec_a2a.testing.boot", "WatchedProcess"),
    "adopted_spawner": ("vaultspec_a2a.testing.boot", "adopted_spawner"),
    "armed_gateway_env": ("vaultspec_a2a.testing.boot", "armed_gateway_env"),
    "await_gateway_ready": ("vaultspec_a2a.testing.boot", "await_gateway_ready"),
    "await_ready": ("vaultspec_a2a.testing.boot", "await_ready"),
    "booted_gateway": ("vaultspec_a2a.testing.boot", "booted_gateway"),
    "broker_gateway_env": ("vaultspec_a2a.testing.boot", "broker_gateway_env"),
    "desktop_workspace": ("vaultspec_a2a.testing.boot", "desktop_workspace"),
    "foreign_worker": ("vaultspec_a2a.testing.boot", "foreign_worker"),
    "gateway_process_env": ("vaultspec_a2a.testing.boot", "gateway_process_env"),
    "gateway_script": ("vaultspec_a2a.testing.boot", "gateway_script"),
    "log_tail": ("vaultspec_a2a.testing.boot", "log_tail"),
    "loopback_callback_bridge": (
        "vaultspec_a2a.testing.boot",
        "loopback_callback_bridge",
    ),
    "read_worker_ipc_secret": (
        "vaultspec_a2a.testing.boot",
        "read_worker_ipc_secret",
    ),
    "reap_process": ("vaultspec_a2a.testing.boot", "reap_process"),
    "seat_app_home": ("vaultspec_a2a.testing.boot", "seat_app_home"),
    "spawn_gateway": ("vaultspec_a2a.testing.boot", "spawn_gateway"),
    "spawn_logged": ("vaultspec_a2a.testing.boot", "spawn_logged"),
    "spawn_signalled": ("vaultspec_a2a.testing.boot", "spawn_signalled"),
    "spawn_until_ready": ("vaultspec_a2a.testing.boot", "spawn_until_ready"),
    "worker_lifecycle_gateway_script": (
        "vaultspec_a2a.testing.boot",
        "worker_lifecycle_gateway_script",
    ),
    "LIVE_PROVIDER_CATALOG_SELECTION_ENVIRON": (
        "vaultspec_a2a.testing.catalog",
        "LIVE_PROVIDER_CATALOG_SELECTION_ENVIRON",
    ),
    "LIVE_PROVIDER_OVERRIDE_SELECTION_ENVIRON": (
        "vaultspec_a2a.testing.catalog",
        "LIVE_PROVIDER_OVERRIDE_SELECTION_ENVIRON",
    ),
    "LIVE_PROVIDER_PREREQUISITES": (
        "vaultspec_a2a.testing.catalog",
        "LIVE_PROVIDER_PREREQUISITES",
    ),
    "NoSelectableLaneError": ("vaultspec_a2a.testing.catalog", "NoSelectableLaneError"),
    "async_catalog_run_fields": (
        "vaultspec_a2a.testing.catalog",
        "async_catalog_run_fields",
    ),
    "async_fetch_in_process_selection": (
        "vaultspec_a2a.testing.catalog",
        "async_fetch_in_process_selection",
    ),
    "async_fetch_provider_catalog": (
        "vaultspec_a2a.testing.catalog",
        "async_fetch_provider_catalog",
    ),
    "catalog_run_fields": ("vaultspec_a2a.testing.catalog", "catalog_run_fields"),
    "declared_lane_model_value": (
        "vaultspec_a2a.testing.catalog",
        "declared_lane_model_value",
    ),
    "fetch_in_process_selection": (
        "vaultspec_a2a.testing.catalog",
        "fetch_in_process_selection",
    ),
    "fetch_in_process_selection_at": (
        "vaultspec_a2a.testing.catalog",
        "fetch_in_process_selection_at",
    ),
    "fetch_provider_catalog": (
        "vaultspec_a2a.testing.catalog",
        "fetch_provider_catalog",
    ),
    "in_process_lane_required": (
        "vaultspec_a2a.testing.catalog",
        "in_process_lane_required",
    ),
    "in_process_lane_selection": (
        "vaultspec_a2a.testing.catalog",
        "in_process_lane_selection",
    ),
    "in_process_selection": ("vaultspec_a2a.testing.catalog", "in_process_selection"),
    "is_selectable": ("vaultspec_a2a.testing.catalog", "is_selectable"),
    "live_provider_catalog_selector_is_configured": (
        "vaultspec_a2a.testing.catalog",
        "live_provider_catalog_selector_is_configured",
    ),
    "live_provider_override_selector_is_configured": (
        "vaultspec_a2a.testing.catalog",
        "live_provider_override_selector_is_configured",
    ),
    "named_lane_selection": ("vaultspec_a2a.testing.catalog", "named_lane_selection"),
    "override_selection_from_served_catalog": (
        "vaultspec_a2a.testing.catalog",
        "override_selection_from_served_catalog",
    ),
    "selection_from_served_catalog": (
        "vaultspec_a2a.testing.catalog",
        "selection_from_served_catalog",
    ),
    "unvalidated_selection": (
        "vaultspec_a2a.testing.catalog",
        "unvalidated_selection",
    ),
    "current_execution_metadata": (
        "vaultspec_a2a.testing.catalog_authority",
        "current_execution_metadata",
    ),
    "DEFAULT_IDLE_WINDOW_S": (
        "vaultspec_a2a.testing.children",
        "DEFAULT_IDLE_WINDOW_S",
    ),
    "await_child": ("vaultspec_a2a.testing.children", "await_child"),
    "child_tree_progress": ("vaultspec_a2a.testing.children", "child_tree_progress"),
    "file_size_fingerprint": (
        "vaultspec_a2a.testing.children",
        "file_size_fingerprint",
    ),
    "measured_child_startup_s": (
        "vaultspec_a2a.testing.children",
        "measured_child_startup_s",
    ),
    "run_child": ("vaultspec_a2a.testing.children", "run_child"),
    "clean_subprocess_environment": (
        "vaultspec_a2a.testing.cli",
        "clean_subprocess_environment",
    ),
    "combined_output": ("vaultspec_a2a.testing.cli", "combined_output"),
    "inherited_environment": ("vaultspec_a2a.testing.cli", "inherited_environment"),
    "run_cli": ("vaultspec_a2a.testing.cli", "run_cli"),
    "ResolvedService": ("vaultspec_a2a.testing.endpoints", "ResolvedService"),
    "resolve_gateway_url": (
        "vaultspec_a2a.testing.endpoints",
        "resolve_gateway_url",
    ),
    "resolve_service": ("vaultspec_a2a.testing.endpoints", "resolve_service"),
    "armed_desktop_app_home": (
        "vaultspec_a2a.testing.environment",
        "armed_desktop_app_home",
    ),
    "prune_stale_dirs": ("vaultspec_a2a.testing.session_root", "prune_stale_dirs"),
    "session_scratch_dir": (
        "vaultspec_a2a.testing.session_root",
        "session_scratch_dir",
    ),
    "TEST_ROOT_NAME": ("vaultspec_a2a.testing.session_root", "TEST_ROOT_NAME"),
    "TestSessionSettings": (
        "vaultspec_a2a.testing.session_root",
        "TestSessionSettings",
    ),
    "seat_test_session": ("vaultspec_a2a.testing.session_root", "seat_test_session"),
    "armed_environment": ("vaultspec_a2a.testing.environment", "armed_environment"),
    "settings_override": ("vaultspec_a2a.testing.environment", "settings_override"),
    "LaneInventoryFactory": ("vaultspec_a2a.testing.factories", "LaneInventoryFactory"),
    "build_settings": ("vaultspec_a2a.testing.factories", "build_settings"),
    "load_settings": ("vaultspec_a2a.testing.factories", "load_settings"),
    "DEFAULT_ATTACH_AUTHORIZATION": (
        "vaultspec_a2a.testing.gateway_verbs",
        "DEFAULT_ATTACH_AUTHORIZATION",
    ),
    "DEFAULT_REQUIRED_ROLE": (
        "vaultspec_a2a.testing.gateway_verbs",
        "DEFAULT_REQUIRED_ROLE",
    ),
    "DEFAULT_TEAM_PRESET": (
        "vaultspec_a2a.testing.gateway_verbs",
        "DEFAULT_TEAM_PRESET",
    ),
    "GatewayVerbs": ("vaultspec_a2a.testing.gateway_verbs", "GatewayVerbs"),
    "async_run_start_body": (
        "vaultspec_a2a.testing.gateway_verbs",
        "async_run_start_body",
    ),
    "gateway_run_verbs": ("vaultspec_a2a.testing.gateway_verbs", "gateway_run_verbs"),
    "role_tokens": ("vaultspec_a2a.testing.gateway_verbs", "role_tokens"),
    "armed_lane_environment": (
        "vaultspec_a2a.testing.lanes",
        "armed_lane_environment",
    ),
    "deterministic_model_assignment": (
        "vaultspec_a2a.testing.lanes",
        "deterministic_model_assignment",
    ),
    "frozen_deterministic_selection": (
        "vaultspec_a2a.testing.lanes",
        "frozen_deterministic_selection",
    ),
    "seated_lanes": ("vaultspec_a2a.testing.lanes", "seated_lanes"),
    "DETERMINISTIC_LANE": ("vaultspec_a2a.testing.lanes", "DETERMINISTIC_LANE"),
    "LANES": ("vaultspec_a2a.testing.lanes", "LANES"),
    "UNATTENDED_REPLY": (
        "vaultspec_a2a.testing.lanes.deterministic",
        "UNATTENDED_REPLY",
    ),
    "DeterministicResearchAdrChatModel": (
        "vaultspec_a2a.testing.lanes.deterministic",
        "DeterministicResearchAdrChatModel",
    ),
    "held_turns": ("vaultspec_a2a.testing.lanes", "held_turns"),
    "register_lanes": ("vaultspec_a2a.testing.lanes", "register_lanes"),
    "add_test_node": ("vaultspec_a2a.testing.graph", "add_test_node"),
    "ainvoke_test_graph": ("vaultspec_a2a.testing.graph", "ainvoke_test_graph"),
    "compile_test_graph": ("vaultspec_a2a.testing.graph", "compile_test_graph"),
    "new_state_graph": ("vaultspec_a2a.testing.graph", "new_state_graph"),
    "stand_in_definition_digest": (
        "vaultspec_a2a.testing.graph",
        "stand_in_definition_digest",
    ),
    "LEASE_TTL_MS": ("vaultspec_a2a.testing.leases", "LEASE_TTL_MS"),
    "Lease": ("vaultspec_a2a.testing.leases", "Lease"),
    "LeaseAcquisitionTimeoutError": (
        "vaultspec_a2a.testing.leases",
        "LeaseAcquisitionTimeoutError",
    ),
    "hold_lease": ("vaultspec_a2a.testing.leases", "hold_lease"),
    "lease_home": ("vaultspec_a2a.testing.leases", "lease_home"),
    "live_shared_holder_count": (
        "vaultspec_a2a.testing.leases",
        "live_shared_holder_count",
    ),
    "plant_link_to_file": ("vaultspec_a2a.testing.links", "plant_link_to_file"),
    "LayerRule": ("vaultspec_a2a.testing.markers", "LayerRule"),
    "apply_layer_markers": ("vaultspec_a2a.testing.markers", "apply_layer_markers"),
    "ClarificationGraph": ("vaultspec_a2a.testing.parking", "ClarificationGraph"),
    "ParkedClarification": ("vaultspec_a2a.testing.parking", "ParkedClarification"),
    "clarification_graph": ("vaultspec_a2a.testing.parking", "clarification_graph"),
    "park_clarification": ("vaultspec_a2a.testing.parking", "park_clarification"),
    "park_document_approval": (
        "vaultspec_a2a.testing.parking",
        "park_document_approval",
    ),
    "park_journaled_permission": (
        "vaultspec_a2a.testing.parking",
        "park_journaled_permission",
    ),
    "park_journaled_permissions": (
        "vaultspec_a2a.testing.parking",
        "park_journaled_permissions",
    ),
    "park_permission": ("vaultspec_a2a.testing.parking", "park_permission"),
    "park_permissions": ("vaultspec_a2a.testing.parking", "park_permissions"),
    "park_plan_approval": ("vaultspec_a2a.testing.parking", "park_plan_approval"),
    "json_list": ("vaultspec_a2a.testing.payloads", "json_list"),
    "json_object": ("vaultspec_a2a.testing.payloads", "json_object"),
    "json_object_list": ("vaultspec_a2a.testing.payloads", "json_object_list"),
    "json_text": ("vaultspec_a2a.testing.payloads", "json_text"),
    "required_bool": ("vaultspec_a2a.testing.payloads", "required_bool"),
    "required_text": ("vaultspec_a2a.testing.payloads", "required_text"),
    "text_list": ("vaultspec_a2a.testing.payloads", "text_list"),
    "is_terminal": ("vaultspec_a2a.testing.polling", "is_terminal"),
    "ok_body": ("vaultspec_a2a.testing.polling", "ok_body"),
    "wait_for_run_status": ("vaultspec_a2a.testing.polling", "wait_for_run_status"),
    "wait_for_run_status_async": (
        "vaultspec_a2a.testing.polling",
        "wait_for_run_status_async",
    ),
    "SCRATCH_ROLE": ("vaultspec_a2a.testing.ports", "SCRATCH_ROLE"),
    "PortAllocationError": ("vaultspec_a2a.testing.ports", "PortAllocationError"),
    "allocate_free_ports": ("vaultspec_a2a.testing.ports", "allocate_free_ports"),
    "free_port": ("vaultspec_a2a.testing.ports", "free_port"),
    "hold_for_process_lifetime": (
        "vaultspec_a2a.testing.ports",
        "hold_for_process_lifetime",
    ),
    "reserve_scratch_ports": (
        "vaultspec_a2a.testing.ports",
        "reserve_scratch_ports",
    ),
    "LivenessWatch": ("vaultspec_a2a.testing.progress", "LivenessWatch"),
    "ProgressDeadline": ("vaultspec_a2a.testing.progress", "ProgressDeadline"),
    "ProgressStalledError": ("vaultspec_a2a.testing.progress", "ProgressStalledError"),
    "ResourceDiedError": ("vaultspec_a2a.testing.progress", "ResourceDiedError"),
    "registry_watch": ("vaultspec_a2a.testing.progress", "registry_watch"),
    "wait_for": ("vaultspec_a2a.testing.progress", "wait_for"),
    "wait_for_async": ("vaultspec_a2a.testing.progress", "wait_for_async"),
    "IMPURE_FIXTURES": ("vaultspec_a2a.testing.purity", "IMPURE_FIXTURES"),
    "SERVICE_MARKER": ("vaultspec_a2a.testing.purity", "SERVICE_MARKER"),
    "forfeits_purity": ("vaultspec_a2a.testing.purity", "forfeits_purity"),
    "uses_impure_fixture": ("vaultspec_a2a.testing.purity", "uses_impure_fixture"),
    "MARKER_NAME": ("vaultspec_a2a.testing.resources", "MARKER_NAME"),
    "RESOURCES": ("vaultspec_a2a.testing.resources", "RESOURCES"),
    "SCRATCH_PREFIX": ("vaultspec_a2a.testing.resources", "SCRATCH_PREFIX"),
    "ResourceClaim": ("vaultspec_a2a.testing.resources", "ResourceClaim"),
    "ResourceDeclarationError": (
        "vaultspec_a2a.testing.resources",
        "ResourceDeclarationError",
    ),
    "ResourceSpec": ("vaultspec_a2a.testing.resources", "ResourceSpec"),
    "declared_claims": ("vaultspec_a2a.testing.resources", "declared_claims"),
    "exclusive_keys": ("vaultspec_a2a.testing.resources", "exclusive_keys"),
    "resolve_spec": ("vaultspec_a2a.testing.resources", "resolve_spec"),
    "elect_status": ("vaultspec_a2a.testing.seeding", "elect_status"),
    "record_completed_checkpoint": (
        "vaultspec_a2a.testing.seeding",
        "record_completed_checkpoint",
    ),
    "seed_accepted_thread": ("vaultspec_a2a.testing.seeding", "seed_accepted_thread"),
    "seed_completed_authority": (
        "vaultspec_a2a.testing.seeding",
        "seed_completed_authority",
    ),
    "seed_create_action": ("vaultspec_a2a.testing.seeding", "seed_create_action"),
    "seed_journaled_thread": (
        "vaultspec_a2a.testing.seeding",
        "seed_journaled_thread",
    ),
    "seed_live_thread": ("vaultspec_a2a.testing.seeding", "seed_live_thread"),
    "seed_thread_expectation": (
        "vaultspec_a2a.testing.seeding",
        "seed_thread_expectation",
    ),
    "CPU_BUDGET_ENV": ("vaultspec_a2a.testing.harness_names", "CPU_BUDGET_ENV"),
    "COMPLETION_ENDPOINT_ENV": (
        "vaultspec_a2a.testing.harness_names",
        "COMPLETION_ENDPOINT_ENV",
    ),
    "COMPLETION_OWNER_PID_ENV": (
        "vaultspec_a2a.testing.harness_names",
        "COMPLETION_OWNER_PID_ENV",
    ),
    "TEST_ENV_PREFIX": ("vaultspec_a2a.testing.harness_names", "TEST_ENV_PREFIX"),
    "SESSION_LEASE_KEY": ("vaultspec_a2a.testing.sessions", "SESSION_LEASE_KEY"),
    "effective_worker_count": (
        "vaultspec_a2a.testing.sessions",
        "effective_worker_count",
    ),
    "live_peer_sessions": ("vaultspec_a2a.testing.sessions", "live_peer_sessions"),
    "machine_cpu_budget": ("vaultspec_a2a.testing.sessions", "machine_cpu_budget"),
    "register_session": ("vaultspec_a2a.testing.sessions", "register_session"),
    "SseFrame": ("vaultspec_a2a.testing.sse", "SseFrame"),
    "SseReader": ("vaultspec_a2a.testing.sse", "SseReader"),
    "decode_frame": ("vaultspec_a2a.testing.sse", "decode_frame"),
    "read_frame": ("vaultspec_a2a.testing.sse", "read_frame"),
    "read_frames_until": ("vaultspec_a2a.testing.sse", "read_frames_until"),
    "JsonReplyHandler": ("vaultspec_a2a.testing.http", "JsonReplyHandler"),
    "health_listener": ("vaultspec_a2a.testing.http", "health_listener"),
    "loopback_uvicorn": ("vaultspec_a2a.testing.http", "loopback_uvicorn"),
    "serve_handler": ("vaultspec_a2a.testing.http", "serve_handler"),
    "serve_on_loopback": ("vaultspec_a2a.testing.http", "serve_on_loopback"),
    "serve_on_loopback_in_thread": (
        "vaultspec_a2a.testing.http",
        "serve_on_loopback_in_thread",
    ),
    "uvicorn_started": ("vaultspec_a2a.testing.http", "uvicorn_started"),
    "RunVerbs": ("vaultspec_a2a.testing.verbs", "RunVerbs"),
    "actor_tokens_body": ("vaultspec_a2a.testing.verbs", "actor_tokens_body"),
    "status_and_json": ("vaultspec_a2a.testing.verbs", "status_and_json"),
    "ServedWorker": ("vaultspec_a2a.testing.worker_app", "ServedWorker"),
    "capacity_holders": ("vaultspec_a2a.testing.worker_app", "capacity_holders"),
    "served_worker": ("vaultspec_a2a.testing.worker_app", "served_worker"),
}


def __getattr__(name: str) -> object:
    """Resolve a facade export only when a caller actually uses it."""
    try:
        module_name, attribute_name = _LAZY_EXPORTS[name]
    except KeyError as exc:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from exc
    value = getattr(import_module(module_name), attribute_name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    """Expose lazy public names to introspection without importing them."""
    return sorted(set(globals()) | set(__all__))


__all__ = [
    "ACP_PROTOCOL_VERSION",
    "ACP_SIMULATOR_PATH",
    "CODER_ROLE",
    "COMPLETION_ENDPOINT_ENV",
    "COMPLETION_OWNER_PID_ENV",
    "CPU_BUDGET_ENV",
    "DEFAULT_ATTACH_AUTHORIZATION",
    "DEFAULT_ATTACH_CREDENTIAL",
    "DEFAULT_IDLE_WINDOW_S",
    "DEFAULT_OWNERSHIP_CAPABILITY",
    "DEFAULT_REQUIRED_ROLE",
    "DEFAULT_TEAM_PRESET",
    "DETERMINISTIC_LANE",
    "FIRST_DEMAND_TIMEOUT",
    "FOREIGN_WORKER_PROGRAM",
    "GATEWAY_AUTH_HEADERS",
    "IMPURE_FIXTURES",
    "LANES",
    "LEASE_TTL_MS",
    "LIVE_PROVIDER_CATALOG_SELECTION_ENVIRON",
    "LIVE_PROVIDER_OVERRIDE_SELECTION_ENVIRON",
    "LIVE_PROVIDER_PREREQUISITES",
    "LOOPBACK_TIMEOUT",
    "MARKER_NAME",
    "MODE_AUTONOMOUS",
    "MODE_MANUAL",
    "OBSERVE_DEADLINE_SECONDS",
    "POLICY_AUTO",
    "POLICY_HUMAN",
    "PRESET_DETERMINISTIC",
    "PRESET_LIVE",
    "READINESS_TIMEOUT",
    "REQUEST_PERMISSION_METHOD",
    "RESOURCES",
    "SCRATCH_PREFIX",
    "SCRATCH_ROLE",
    "SERVICE_MARKER",
    "SESSION_LEASE_KEY",
    "SOLO_CODER_PRESET",
    "TEST_ENV_PREFIX",
    "TEST_ROOT_NAME",
    "UNATTENDED_REPLY",
    "AcceptanceCase",
    "AcceptanceHarness",
    "BootedGateway",
    "ClarificationGraph",
    "DeterministicResearchAdrChatModel",
    "GatewayBootError",
    "GatewayVerbs",
    "JsonReplyHandler",
    "LaneInventoryFactory",
    "LayerRule",
    "Lease",
    "LeaseAcquisitionTimeoutError",
    "LivenessWatch",
    "Materialization",
    "NoSelectableLaneError",
    "ParkedClarification",
    "PortAllocationError",
    "ProgressDeadline",
    "ProgressStalledError",
    "ResilientAuthoringClient",
    "ResolvedService",
    "ResourceClaim",
    "ResourceDeclarationError",
    "ResourceDiedError",
    "ResourceSpec",
    "RunVerbs",
    "ServedWorker",
    "SignalledChild",
    "SseFrame",
    "SseReader",
    "TestSessionSettings",
    "WatchedProcess",
    "acp_request",
    "actor_tokens_body",
    "add_test_node",
    "adopted_spawner",
    "ainvoke_test_graph",
    "allocate_free_ports",
    "antigravity_credential_path",
    "apply_layer_markers",
    "armed_desktop_app_home",
    "armed_environment",
    "armed_gateway_env",
    "armed_lane_environment",
    "async_catalog_run_fields",
    "async_fetch_in_process_selection",
    "async_fetch_provider_catalog",
    "async_run_start_body",
    "await_child",
    "await_gateway_ready",
    "await_ready",
    "booted_gateway",
    "broker_gateway_env",
    "build_settings",
    "capacity_holders",
    "catalog_run_fields",
    "child_tree_progress",
    "clarification_graph",
    "clean_subprocess_environment",
    "combined_output",
    "compile_test_graph",
    "current_execution_metadata",
    "declared_claims",
    "declared_lane_model_value",
    "decode_frame",
    "desktop_workspace",
    "deterministic_model_assignment",
    "effective_worker_count",
    "elect_status",
    "exchange_acp_request",
    "exclusive_keys",
    "extract_bridge_tools",
    "fetch_in_process_selection",
    "fetch_in_process_selection_at",
    "fetch_provider_catalog",
    "file_size_fingerprint",
    "foreign_worker",
    "forfeits_purity",
    "free_port",
    "frozen_deterministic_selection",
    "gateway_process_env",
    "gateway_run_verbs",
    "gateway_script",
    "health_listener",
    "held_turns",
    "hold_for_process_lifetime",
    "hold_lease",
    "in_process_lane_required",
    "in_process_lane_selection",
    "in_process_selection",
    "inherited_environment",
    "initialize_request",
    "initialize_result",
    "is_live_lane",
    "is_selectable",
    "is_terminal",
    "json_list",
    "json_object",
    "json_object_list",
    "json_text",
    "lease_home",
    "live_peer_sessions",
    "live_provider_catalog_selector_is_configured",
    "live_provider_override_selector_is_configured",
    "live_shared_holder_count",
    "load_settings",
    "log_tail",
    "loopback_callback_bridge",
    "loopback_uvicorn",
    "machine_cpu_budget",
    "measured_child_startup_s",
    "message_content",
    "mint_raw_token",
    "named_lane_selection",
    "new_state_graph",
    "observe_bridged_authoring_run",
    "ok_body",
    "override_selection_from_served_catalog",
    "park_clarification",
    "park_document_approval",
    "park_journaled_permission",
    "park_journaled_permissions",
    "park_permission",
    "park_permissions",
    "park_plan_approval",
    "plant_link_to_file",
    "prune_stale_dirs",
    "reachable_stack",
    "read_acp_frame",
    "read_frame",
    "read_frames_until",
    "read_worker_ipc_secret",
    "reap_process",
    "record_completed_checkpoint",
    "register_lanes",
    "register_session",
    "registry_watch",
    "request_permission_params",
    "request_permission_request",
    "required_bool",
    "required_text",
    "reserve_scratch_ports",
    "resolve_gateway_url",
    "resolve_selection",
    "resolve_service",
    "resolve_spec",
    "role_tokens",
    "run_child",
    "run_cli",
    "runtime_budget_for",
    "seat_app_home",
    "seat_test_session",
    "seated_lanes",
    "seed_accepted_thread",
    "seed_completed_authority",
    "seed_create_action",
    "seed_journaled_thread",
    "seed_live_thread",
    "seed_thread_expectation",
    "selection_from_served_catalog",
    "serve_handler",
    "serve_on_loopback",
    "serve_on_loopback_in_thread",
    "served_worker",
    "session_scratch_dir",
    "settings_override",
    "simulator_command",
    "snapshot_vault",
    "spawn_gateway",
    "spawn_logged",
    "spawn_signalled",
    "spawn_until_ready",
    "stand_in_definition_digest",
    "status_and_json",
    "text_list",
    "unvalidated_selection",
    "uses_impure_fixture",
    "uvicorn_started",
    "vault_write_delta",
    "wait_for",
    "wait_for_async",
    "wait_for_run_status",
    "wait_for_run_status_async",
    "worker_lifecycle_gateway_script",
]
