"""Git hook installer for the repo-local prek pipeline.

The generated hook is intentionally path-agnostic:

- it resolves the active worktree root at runtime via ``git rev-parse``
- it runs ``prek`` through ``uv run`` instead of a hardcoded executable path
- it keeps ``PREK_HOME`` and ``UV_CACHE_DIR`` inside the repo to avoid
  user-profile-specific state during hook execution

This module is invoked by the Justfile, not exposed on the production CLI.
"""

from __future__ import annotations

__all__ = ["install_hook", "main", "remove_hook"]

import argparse
import stat
import subprocess
import sys
from pathlib import Path

_MANAGED_MARKER = "Managed by vaultspec_a2a.control.hooks"
_SCRIPT_VERSION = 4
_SUPPORTED_HOOKS = ("pre-commit",)


def _git_stdout(repo_root: Path, *args: str) -> str:
    completed = subprocess.run(
        ["git", *args],
        cwd=repo_root,
        capture_output=True,
        text=True,
        check=True,
    )
    return completed.stdout.strip()


def _resolve_repo_root(repo_root: Path | None = None) -> Path:
    candidate = (repo_root or Path.cwd()).resolve()
    root = _git_stdout(candidate, "rev-parse", "--show-toplevel")
    return Path(root)


def _resolve_hooks_dir(repo_root: Path) -> Path:
    hooks_dir = _git_stdout(repo_root, "rev-parse", "--git-path", "hooks")
    path = Path(hooks_dir)
    return path if path.is_absolute() else repo_root / path


def _hook_script(hook_type: str) -> str:
    return "\n".join(
        [
            "#!/bin/sh",
            f"# {_MANAGED_MARKER}",
            "# Path-agnostic prek shim for all worktrees in this checkout.",
            "set -eu",
            "",
            'HERE="$(cd "$(dirname "$0")" && pwd)"',
            'ROOT="$(git rev-parse --show-toplevel 2>/dev/null)"',
            'if [ -z "$ROOT" ]; then',
            '    echo "prek hook: unable to resolve repository root" >&2',
            "    exit 1",
            "fi",
            "",
            'export UV_CACHE_DIR="${UV_CACHE_DIR:-$ROOT/.uv-cache}"',
            'export PREK_HOME="${PREK_HOME:-$ROOT/.prek-home}"',
            "",
            "if ! command -v uv >/dev/null 2>&1; then",
            '    echo "prek hook: `uv` must be available on PATH" >&2',
            "    exit 1",
            "fi",
            "",
            'exec uv run --project "$ROOT" --no-default-groups --group dev '
            "--no-sync --frozen \\",
            '    prek hook-impl --hook-dir "$HERE" '
            f"--script-version {_SCRIPT_VERSION} \\",
            f'    --hook-type={hook_type} -- "$@"',
            "",
        ]
    )


def _is_managed_hook(text: str) -> bool:
    return _MANAGED_MARKER in text or "File generated by prek" in text


def install_hook(
    hook_type: str = "pre-commit",
    *,
    repo_root: Path | None = None,
    force: bool = False,
) -> Path:
    if hook_type not in _SUPPORTED_HOOKS:
        msg = f"unsupported hook type: {hook_type}"
        raise ValueError(msg)

    resolved_root = _resolve_repo_root(repo_root)
    hooks_dir = _resolve_hooks_dir(resolved_root)
    hooks_dir.mkdir(parents=True, exist_ok=True)
    hook_path = hooks_dir / hook_type

    if hook_path.exists():
        existing = hook_path.read_text(encoding="utf-8")
        if not force and not _is_managed_hook(existing):
            msg = (
                f"refusing to overwrite unmanaged hook: {hook_path}. "
                "Re-run with --force if replacement is intentional."
            )
            raise RuntimeError(msg)

    hook_path.write_text(_hook_script(hook_type), encoding="utf-8", newline="\n")
    current_mode = hook_path.stat().st_mode
    hook_path.chmod(current_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return hook_path


def remove_hook(
    hook_type: str = "pre-commit",
    *,
    repo_root: Path | None = None,
    force: bool = False,
) -> bool:
    if hook_type not in _SUPPORTED_HOOKS:
        msg = f"unsupported hook type: {hook_type}"
        raise ValueError(msg)

    resolved_root = _resolve_repo_root(repo_root)
    hook_path = _resolve_hooks_dir(resolved_root) / hook_type
    if not hook_path.exists():
        return False

    existing = hook_path.read_text(encoding="utf-8")
    if not force and not _is_managed_hook(existing):
        msg = (
            f"refusing to remove unmanaged hook: {hook_path}. "
            "Re-run with --force if removal is intentional."
        )
        raise RuntimeError(msg)

    hook_path.unlink()
    return True


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="python -m vaultspec_a2a.control.hooks",
        description="Install or remove the repo-managed prek Git hook shim.",
    )
    parser.add_argument(
        "command",
        choices=["install", "remove", "path"],
        help="Action to perform.",
    )
    parser.add_argument(
        "--hook-type",
        default="pre-commit",
        choices=_SUPPORTED_HOOKS,
        help="Hook to manage (default: pre-commit).",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Allow replacement or removal of unmanaged hook files.",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = _build_parser()
    args = parser.parse_args(argv)

    try:
        if args.command == "install":
            path = install_hook(args.hook_type, force=args.force)
            print(path)
            return 0
        if args.command == "remove":
            removed = remove_hook(args.hook_type, force=args.force)
            print("removed" if removed else "missing")
            return 0

        path = _resolve_hooks_dir(_resolve_repo_root()) / args.hook_type
        print(path)
        return 0
    except (RuntimeError, subprocess.CalledProcessError, ValueError) as exc:
        print(str(exc), file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
