/**
 * This file was auto-generated by openapi-typescript from the live OpenAPI spec.
 * REST schemas below are generated; WebSocket protocol types at the bottom
 * are hand-authored from Pydantic models (not in OpenAPI).
 *
 * Regenerate REST section: npx openapi-typescript http://localhost:8000/openapi.json -o src/app/data/wire-types.ts
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Public health endpoint aggregating gateway, worker, and database status.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Threads Endpoint
         * @description List orchestration threads with pagination and optional status filter.
         */
        get: operations["list_threads_endpoint_api_threads_get"];
        put?: never;
        /**
         * Create Thread Endpoint
         * @description Create a new orchestration thread and dispatch to the worker.
         */
        post: operations["create_thread_endpoint_api_threads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/threads/{thread_id}/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Thread Metadata Endpoint
         * @description Return the full ThreadMetadata object for a thread.
         */
        get: operations["get_thread_metadata_endpoint_api_threads__thread_id__metadata_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/threads/{thread_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Thread Endpoint
         * @description Hard-delete a thread and all cascading artifacts.
         */
        delete: operations["delete_thread_endpoint_api_threads__thread_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/threads/{thread_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Archive Thread Endpoint
         * @description Transition a thread to ARCHIVED status.
         */
        post: operations["archive_thread_endpoint_api_threads__thread_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/threads/{thread_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Thread Events
         * @description Stream thread events over SSE for clients that do not use WebSockets.
         */
        get: operations["stream_thread_events_api_threads__thread_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/threads/{thread_id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Thread State Endpoint
         * @description Return a complete thread state snapshot for client reconnection.
         *
         *     The ``last_sequence`` field enables gap detection: the client discards
         *     any subsequent WebSocket events with ``sequence <= last_sequence``
         *     (ADR-011 section 2.3).
         */
        get: operations["get_thread_state_endpoint_api_threads__thread_id__state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/threads/{thread_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Message Endpoint
         * @description Send a user message into an existing thread.
         *
         *     Returns 202 Accepted immediately; the message is dispatched to the
         *     worker process for graph execution (ADR-019).
         */
        post: operations["send_message_endpoint_api_threads__thread_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/threads/{thread_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Thread Endpoint
         * @description Cancel a running thread by dispatching a cancel action to the worker.
         */
        post: operations["cancel_thread_endpoint_api_threads__thread_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/team/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Team Status Endpoint
         * @description Return current team status: agents, active threads, pending permissions.
         */
        get: operations["get_team_status_endpoint_api_team_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Team Presets Endpoint
         * @description Return all available team presets for the team picker UI.
         */
        get: operations["list_team_presets_endpoint_api_teams_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/permissions/{request_id}/respond": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Respond To Permission Endpoint
         * @description Submit a permission response via REST for guaranteed delivery.
         */
        post: operations["respond_to_permission_endpoint_api_permissions__request_id__respond_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/shutdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Shutdown Endpoint
         * @description Initiate graceful server shutdown.
         */
        post: operations["shutdown_endpoint_api_admin_shutdown_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Internal Health
         * @description Readiness probe -- confirms the internal API is accepting connections.
         */
        get: operations["internal_health_internal_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Receive Worker Event
         * @description Receive a single event from the worker and relay to browser clients.
         *
         *     The ``WorkerBridge`` in the worker process POSTs here instead of
         *     sending a WebSocket frame.  The payload format matches
         *     ``WorkerEventEnvelope``.
         */
        post: operations["receive_worker_event_internal_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/events/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Receive Worker Event Batch
         * @description Receive a batch of events from the worker (CRIT-02).
         *
         *     The ``WorkerBridge`` accumulates events for a short interval then
         *     POSTs them as a single ``{"events": [...]}`` payload.  Each entry
         *     has the same shape as a single-event envelope (``thread_id`` +
         *     ``payload``).
         */
        post: operations["receive_worker_event_batch_internal_events_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Receive Worker Heartbeat
         * @description Receive a heartbeat from the worker.
         *
         *     Updates ``app.state`` so the gateway can monitor worker
         *     liveness without a persistent WebSocket connection.
         */
        post: operations["receive_worker_heartbeat_internal_heartbeat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Endpoint
         * @description Top-level liveness check for external probes.
         *
         *     `/health` stays green when the gateway process is alive. Aggregate
         *     dependency readiness is exposed separately via `/api/health`.
         */
        get: operations["health_endpoint_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentLifecycleState
         * @description Observable agent states exposed to the frontend.
         *
         *     Maps to ADR-003 MCP states. Distinct from ``AgentState`` which tracks
         *     internal process lifecycle (init/ready/running/error/done).
         * @enum {string}
         */
        AgentLifecycleState: "submitted" | "idle" | "working" | "input_required" | "auth_required" | "completed" | "failed" | "cancelled";
        /**
         * AgentStatusEntry
         * @description Agent status within a team status response.
         */
        AgentStatusEntry: {
            /** Agent Id */
            agent_id: string;
            /** Node Name */
            node_name: string;
            state: components["schemas"]["AgentLifecycleState"];
            provider?: components["schemas"]["Provider"] | null;
            model?: components["schemas"]["Model"] | null;
            /**
             * Role
             * @default
             */
            role: string;
            /**
             * Display Name
             * @default
             */
            display_name: string;
            /**
             * Description
             * @default
             */
            description: string;
        };
        /**
         * ArtifactSnapshot
         * @description Fully materialized file artifact.
         */
        ArtifactSnapshot: {
            /** Artifact Id */
            artifact_id: string;
            /** Filename */
            filename: string;
            /** Content */
            content: string;
            /** Complete */
            complete: boolean;
        };
        /**
         * CancelThreadResponse
         * @description Response after requesting thread cancellation.
         */
        CancelThreadResponse: {
            /** Thread Id */
            thread_id: string;
            /** Status */
            status: string;
            /** Cancelled */
            cancelled: boolean;
            /**
             * Accepted
             * @default false
             */
            accepted: boolean;
            /**
             * Applied
             * @default false
             */
            applied: boolean;
            /**
             * Action Status
             * @default rejected_invalid_state
             */
            action_status: string;
            /** Action Id */
            action_id?: string | null;
            /** Idempotency Key */
            idempotency_key?: string | null;
        };
        /**
         * ContextRef
         * @description Reference to a context document in the .vault hierarchy.
         */
        ContextRef: {
            /** Path */
            path: string;
            /** Stage */
            stage: string;
            /**
             * Summary
             * @default
             */
            summary: string;
        };
        /**
         * CreateThreadRequest
         * @description Create a new orchestration thread.
         */
        CreateThreadRequest: {
            /** Title */
            title?: string | null;
            /** Initial Message */
            initial_message: string;
            /** Team Preset */
            team_preset?: string | null;
            metadata?: components["schemas"]["ThreadMetadata"] | null;
            /** Nickname */
            nickname?: string | null;
            /** Autonomous */
            autonomous?: boolean | null;
        };
        /**
         * CreateThreadResponse
         * @description Response after successfully creating a thread.
         */
        CreateThreadResponse: {
            /** Thread Id */
            thread_id: string;
            /** Status */
            status: string;
            /** Nickname */
            nickname?: string | null;
        };
        /**
         * ExecutionTaskSnapshot
         * @description Normalized execution task used in reconnect snapshots.
         */
        ExecutionTaskSnapshot: {
            /** Task Id */
            task_id: string;
            /** Name */
            name: string;
            /** Path */
            path?: string[];
            /**
             * Has Error
             * @default false
             */
            has_error: boolean;
            /** Error Type */
            error_type?: string | null;
            /** Interrupt Ids */
            interrupt_ids?: string[];
            /** Interrupt Types */
            interrupt_types?: string[];
            /**
             * Has Nested State
             * @default false
             */
            has_nested_state: boolean;
            /**
             * Has Result
             * @default false
             */
            has_result: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * MessageSnapshot
         * @description Fully materialized message in a thread replay.
         */
        MessageSnapshot: {
            /** Message Id */
            message_id: string;
            /** Role */
            role: string;
            /** Content */
            content: string;
            /** Agent Id */
            agent_id?: string | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /**
         * Model
         * @description LLM capability levels.
         *
         *     Abstracts specific version strings to reduce maintenance burden.
         * @enum {string}
         */
        Model: "low" | "mid" | "high" | "max";
        /**
         * PendingPermission
         * @description Outstanding permission request summary.
         */
        PendingPermission: {
            /** Request Id */
            request_id: string;
            /** Thread Id */
            thread_id: string;
            /** Description */
            description: string;
            /**
             * Request Status
             * @default pending
             */
            request_status: string;
        };
        /**
         * PermissionOptionKind
         * @description User permission response options (mirrors ACP PermissionOption.kind).
         *
         *     Values:
         *         ALLOW_ONCE: Allow the tool call this time only.
         *         ALLOW_ALWAYS: Allow all future invocations of this tool without prompting.
         *         REJECT_ONCE: Deny the tool call this time only.
         *         REJECT_ALWAYS: Deny all future invocations of this tool without prompting.
         * @enum {string}
         */
        PermissionOptionKind: "allow_once" | "allow_always" | "reject_once" | "reject_always";
        /**
         * PermissionResponseRequest
         * @description Submit a permission response via REST (guaranteed delivery).
         */
        PermissionResponseRequest: {
            /** Option Id */
            option_id: string;
            kind?: components["schemas"]["PermissionOptionKind"] | null;
        };
        /**
         * PermissionResponseResult
         * @description Result of submitting a permission response.
         */
        PermissionResponseResult: {
            /** Request Id */
            request_id: string;
            /** Accepted */
            accepted: boolean;
            /**
             * Applied
             * @default false
             */
            applied: boolean;
            /**
             * Action Status
             * @default rejected_invalid_state
             */
            action_status: string;
            /** Thread Id */
            thread_id: string;
            /** Action Id */
            action_id?: string | null;
            /** Idempotency Key */
            idempotency_key?: string | null;
            /** Approval Status */
            approval_status?: string | null;
        };
        /** PlanEntry */
        PlanEntry: {
            /** Content */
            content: string;
            /**
             * Status
             * @default pending
             */
            status: string;
            /**
             * Priority
             * @default medium
             */
            priority: string;
        };
        /**
         * Provider
         * @description Supported LLM providers.
         * @enum {string}
         */
        Provider: "claude" | "gemini" | "mock" | "openai" | "zhipu";
        /**
         * SendMessageRequest
         * @description Send a user message into an existing thread via REST.
         */
        SendMessageRequest: {
            /** Content */
            content: string;
            /** Agent Id */
            agent_id?: string | null;
        };
        /**
         * SendMessageResponse
         * @description Response after accepting a user message (202 Accepted).
         */
        SendMessageResponse: {
            /** Status */
            status: string;
            /** Thread Id */
            thread_id: string;
            /**
             * Accepted
             * @default true
             */
            accepted: boolean;
            /**
             * Applied
             * @default false
             */
            applied: boolean;
            /**
             * Action Status
             * @default accepted_not_applied
             */
            action_status: string;
            /** Action Id */
            action_id?: string | null;
            /** Idempotency Key */
            idempotency_key?: string | null;
        };
        /**
         * TeamPresetSummary
         * @description Lightweight team preset descriptor for the team picker UI (ADR-013 §6).
         */
        TeamPresetSummary: {
            /** Id */
            id: string;
            /** Display Name */
            display_name: string;
            /** Description */
            description: string;
            /** Topology */
            topology: string;
            /** Worker Count */
            worker_count: number;
        };
        /**
         * TeamPresetsResponse
         * @description Response for GET /teams: list of available team presets (ADR-013 §6).
         */
        TeamPresetsResponse: {
            /** Presets */
            presets: components["schemas"]["TeamPresetSummary"][];
        };
        /**
         * TeamStatusResponse
         * @description Current team status snapshot via REST.
         */
        TeamStatusResponse: {
            /** Agents */
            agents: components["schemas"]["AgentStatusEntry"][];
            /** Active Threads */
            active_threads: string[];
            /** Pending Permissions */
            pending_permissions: components["schemas"]["PendingPermission"][];
        };
        /**
         * ThreadListResponse
         * @description Paginated thread listing.
         */
        ThreadListResponse: {
            /** Threads */
            threads: components["schemas"]["ThreadSummary"][];
            /** Total */
            total: number;
        };
        /**
         * ThreadMetadata
         * @description Provenance and context attached to an orchestration thread.
         */
        ThreadMetadata: {
            /**
             * Nickname
             * @default
             */
            nickname: string;
            /** Workspace Root */
            workspace_root: string;
            /**
             * Source Repo
             * @default
             */
            source_repo: string;
            /**
             * Source Branch
             * @default
             */
            source_branch: string;
            /**
             * Callee
             * @default
             */
            callee: string;
            /**
             * Feature Tag
             * @default
             */
            feature_tag: string;
            /** Context Refs */
            context_refs?: components["schemas"]["ContextRef"][];
        };
        /**
         * ThreadStateSnapshot
         * @description Complete thread state for reconnection replay.
         *
         *     The client fetches this via REST, notes ``last_sequence``, then
         *     discards any WebSocket events with ``sequence <= last_sequence``.
         */
        ThreadStateSnapshot: {
            /** Thread Id */
            thread_id: string;
            /** Status */
            status: string;
            /** Messages */
            messages?: components["schemas"]["MessageSnapshot"][];
            /** Tool Calls */
            tool_calls?: components["schemas"]["ToolCallSnapshot"][];
            /** Pending Permissions */
            pending_permissions?: components["schemas"]["_PermissionSnapshot"][];
            /** Artifacts */
            artifacts?: components["schemas"]["ArtifactSnapshot"][];
            /** Plan */
            plan?: components["schemas"]["PlanEntry"][];
            /** Agents */
            agents?: components["schemas"]["_AgentSnapshot"][];
            /** Last Sequence */
            last_sequence: number;
            /** Checkpoint Id */
            checkpoint_id?: string | null;
            /** Checkpoint Created At */
            checkpoint_created_at?: string | null;
            /** Checkpoint Parent Id */
            checkpoint_parent_id?: string | null;
            /** Checkpoint Source */
            checkpoint_source?: string | null;
            /** Checkpoint Step */
            checkpoint_step?: number | null;
            /** Checkpoint Updated Channels */
            checkpoint_updated_channels?: string[];
            /** Pending Write Channels */
            pending_write_channels?: string[];
            /**
             * Pending Write Count
             * @default 0
             */
            pending_write_count: number;
            /** History Depth */
            history_depth?: number | null;
            /** Next Nodes */
            next_nodes?: string[];
            /**
             * Task Count
             * @default 0
             */
            task_count: number;
            /**
             * Pending Interrupt Count
             * @default 0
             */
            pending_interrupt_count: number;
            /** Execution Tasks */
            execution_tasks?: components["schemas"]["ExecutionTaskSnapshot"][];
            /**
             * Snapshot Complete
             * @default true
             */
            snapshot_complete: boolean;
            /** Degraded Reasons */
            degraded_reasons?: string[];
            /**
             * Replay Status
             * @default unknown
             */
            replay_status: string;
            /** Repair Status */
            repair_status?: string | null;
            /** Execution Readiness */
            execution_readiness?: string | null;
            /** Pause Cause */
            pause_cause?: string | null;
            /** Approval Status */
            approval_status?: string | null;
            /** Approval Request Id */
            approval_request_id?: string | null;
        };
        /**
         * ThreadSummary
         * @description Lightweight thread descriptor for list endpoints.
         */
        ThreadSummary: {
            /** Thread Id */
            thread_id: string;
            /** Title */
            title?: string | null;
            /** Status */
            status: string;
            /** Repair Status */
            repair_status?: string | null;
            /** Execution Readiness */
            execution_readiness?: string | null;
            /** Approval Status */
            approval_status?: string | null;
            /** Approval Request Id */
            approval_request_id?: string | null;
            agent_state?: components["schemas"]["AgentLifecycleState"] | null;
            /** Team Preset */
            team_preset?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Nickname */
            nickname?: string | null;
            /** Feature Tag */
            feature_tag?: string | null;
            /** Source Branch */
            source_branch?: string | null;
            /** Callee */
            callee?: string | null;
        };
        /**
         * ToolCallContentDiff
         * @description Diff content block within a tool call.
         */
        ToolCallContentDiff: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            content_type: "diff";
            /** Path */
            path: string;
            /** Old Text */
            old_text?: string | null;
            /** New Text */
            new_text: string;
        };
        /**
         * ToolCallContentTerminal
         * @description Terminal output content block within a tool call.
         */
        ToolCallContentTerminal: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            content_type: "terminal";
            /** Terminal Id */
            terminal_id: string;
        };
        /**
         * ToolCallContentText
         * @description Plain text content block within a tool call.
         */
        ToolCallContentText: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            content_type: "text";
            /** Text */
            text: string;
        };
        /**
         * ToolCallLocation
         * @description File location associated with a tool call.
         */
        ToolCallLocation: {
            /** Path */
            path: string;
            /** Line */
            line?: number | null;
        };
        /**
         * ToolCallSnapshot
         * @description Fully materialized tool call (all incremental updates merged).
         */
        ToolCallSnapshot: {
            /** Tool Call Id */
            tool_call_id: string;
            /** Title */
            title: string;
            kind: components["schemas"]["ToolKind"];
            status: components["schemas"]["ToolCallStatus"];
            /** Locations */
            locations?: components["schemas"]["ToolCallLocation"][];
            /** Content */
            content?: (components["schemas"]["ToolCallContentText"] | components["schemas"]["ToolCallContentDiff"] | components["schemas"]["ToolCallContentTerminal"])[];
        };
        /**
         * ToolCallStatus
         * @description Lifecycle states for a single tool invocation.
         * @enum {string}
         */
        ToolCallStatus: "pending" | "in_progress" | "completed" | "failed";
        /**
         * ToolKind
         * @description ACP tool categories (mirrors agentclientprotocol.com schema).
         * @enum {string}
         */
        ToolKind: "read" | "edit" | "delete" | "move" | "search" | "execute" | "think" | "fetch" | "switch_mode" | "other";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * _AgentSnapshot
         * @description Agent state within a thread snapshot.
         */
        _AgentSnapshot: {
            /** Agent Id */
            agent_id: string;
            /** Node Name */
            node_name: string;
            state: components["schemas"]["AgentLifecycleState"];
            provider?: components["schemas"]["Provider"] | null;
            model?: components["schemas"]["Model"] | null;
            /**
             * Role
             * @default
             */
            role: string;
            /**
             * Display Name
             * @default
             */
            display_name: string;
            /**
             * Description
             * @default
             */
            description: string;
        };
        /**
         * _PermissionOptionSnapshot
         * @description Permission option within a snapshot.
         */
        _PermissionOptionSnapshot: {
            /** Option Id */
            option_id: string;
            /** Name */
            name: string;
            kind: components["schemas"]["PermissionOptionKind"];
        };
        /**
         * _PermissionSnapshot
         * @description Outstanding permission request in a state snapshot.
         */
        _PermissionSnapshot: {
            /** Request Id */
            request_id: string;
            /** Description */
            description: string;
            /** Options */
            options: components["schemas"]["_PermissionOptionSnapshot"][];
            /** Tool Call */
            tool_call?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_threads_endpoint_api_threads_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_thread_endpoint_api_threads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateThreadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateThreadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_thread_metadata_endpoint_api_threads__thread_id__metadata_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadMetadata"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_thread_endpoint_api_threads__thread_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_thread_endpoint_api_threads__thread_id__archive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_thread_events_api_threads__thread_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_thread_state_endpoint_api_threads__thread_id__state_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadStateSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_message_endpoint_api_threads__thread_id__messages_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendMessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_thread_endpoint_api_threads__thread_id__cancel_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelThreadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_team_status_endpoint_api_team_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamStatusResponse"];
                };
            };
        };
    };
    list_team_presets_endpoint_api_teams_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamPresetsResponse"];
                };
            };
        };
    };
    respond_to_permission_endpoint_api_permissions__request_id__respond_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PermissionResponseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionResponseResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    shutdown_endpoint_api_admin_shutdown_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    internal_health_internal_health_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    receive_worker_event_internal_events_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    receive_worker_event_batch_internal_events_batch_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    receive_worker_heartbeat_internal_heartbeat_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_endpoint_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}

// ---------------------------------------------------------------------------
// WebSocket protocol types (hand-authored from Pydantic schemas)
// These are NOT in the OpenAPI spec because WS is not a REST endpoint.
// ---------------------------------------------------------------------------

/** Server event type discriminator values. */
export type ServerEventType =
    | "agent_status"
    | "message_chunk"
    | "thought_chunk"
    | "tool_call_start"
    | "tool_call_update"
    | "permission_request"
    | "artifact_update"
    | "plan_update"
    | "team_status"
    | "error"
    | "connected"
    | "heartbeat";

/** Client command type discriminator values. */
export type ClientCommandType =
    | "subscribe"
    | "unsubscribe"
    | "send_message"
    | "permission_response"
    | "agent_control"
    | "ping";

/** Agent control actions. */
export type AgentControlAction = "pause" | "resume" | "terminate";

/** ToolCallContent discriminated union — text, diff, or terminal block. */
export type WsToolCallContent =
    | { content_type: "text"; text: string }
    | { content_type: "diff"; path: string; old_text: string | null; new_text: string }
    | { content_type: "terminal"; terminal_id: string };

/** Permission option within a permission request event. */
export interface WsPermissionOption {
    option_id: string;
    name: string;
    kind: components["schemas"]["PermissionOptionKind"];
}

/** Agent summary within a team status event. */
export interface WsAgentSummary {
    agent_id: string;
    node_name: string;
    state: components["schemas"]["AgentLifecycleState"];
    provider: components["schemas"]["Provider"] | null;
    model: components["schemas"]["Model"] | null;
    role: string;
    display_name: string;
    description: string;
}

// -- Thread-scoped events (extend EventEnvelope base) --

interface EventEnvelope {
    type: ServerEventType;
    thread_id: string;
    agent_id: string | null;
    timestamp: string;
    sequence: number;
    metadata?: Record<string, unknown> | null;
}

export interface AgentStatusEvent extends EventEnvelope {
    type: "agent_status";
    state: components["schemas"]["AgentLifecycleState"];
    node_name: string;
    detail?: string | null;
}

export interface MessageChunkEvent extends EventEnvelope {
    type: "message_chunk";
    content: string;
    message_id: string;
    finish_reason?: string | null;
}

export interface ThoughtChunkEvent extends EventEnvelope {
    type: "thought_chunk";
    content: string;
    message_id: string;
}

export interface ToolCallStartEvent extends EventEnvelope {
    type: "tool_call_start";
    tool_call_id: string;
    title: string;
    kind: components["schemas"]["ToolKind"];
    status: components["schemas"]["ToolCallStatus"];
    locations: components["schemas"]["ToolCallLocation"][];
    content: WsToolCallContent[];
}

export interface ToolCallUpdateEvent extends EventEnvelope {
    type: "tool_call_update";
    tool_call_id: string;
    title?: string | null;
    kind?: components["schemas"]["ToolKind"] | null;
    status?: components["schemas"]["ToolCallStatus"] | null;
    locations?: components["schemas"]["ToolCallLocation"][] | null;
    content?: WsToolCallContent[] | null;
}

export interface PermissionRequestEvent extends EventEnvelope {
    type: "permission_request";
    request_id: string;
    description: string;
    options: WsPermissionOption[];
    tool_call?: string | null;
    tool_kind?: components["schemas"]["ToolKind"] | null;
}

export interface ArtifactUpdateEvent extends EventEnvelope {
    type: "artifact_update";
    artifact_id: string;
    filename: string;
    content: string;
    append: boolean;
    last_chunk: boolean;
}

export interface PlanUpdateEvent extends EventEnvelope {
    type: "plan_update";
    entries: components["schemas"]["PlanEntry"][];
}

export interface TeamStatusEvent extends EventEnvelope {
    type: "team_status";
    agents: WsAgentSummary[];
    active_thread_ids: string[];
}

export interface ErrorEvent extends EventEnvelope {
    type: "error";
    code: string;
    message: string;
    recoverable: boolean;
}

// -- Connection-scoped events (NOT thread-scoped, no envelope) --

export interface ConnectedEvent {
    type: "connected";
    client_id: string;
    server_version: string;
    active_threads: string[];
    metadata?: Record<string, unknown> | null;
}

export interface HeartbeatEvent {
    type: "heartbeat";
    timestamp: string;
    server_uptime_seconds: number;
    metadata?: Record<string, unknown> | null;
}

/** Discriminated union of all server-to-client events. */
export type ServerEvent =
    | AgentStatusEvent
    | MessageChunkEvent
    | ThoughtChunkEvent
    | ToolCallStartEvent
    | ToolCallUpdateEvent
    | PermissionRequestEvent
    | ArtifactUpdateEvent
    | PlanUpdateEvent
    | TeamStatusEvent
    | ErrorEvent
    | ConnectedEvent
    | HeartbeatEvent;

// -- Client-to-server commands --

interface ClientCommandBase {
    type: ClientCommandType;
    request_id?: string | null;
}

export interface SubscribeCommand extends ClientCommandBase {
    type: "subscribe";
    thread_ids: string[];
}

export interface UnsubscribeCommand extends ClientCommandBase {
    type: "unsubscribe";
    thread_ids: string[];
}

export interface SendMessageCommand extends ClientCommandBase {
    type: "send_message";
    thread_id: string;
    content: string;
    agent_id?: string | null;
}

export interface AgentControlCommand extends ClientCommandBase {
    type: "agent_control";
    thread_id: string;
    agent_id: string;
    action: AgentControlAction;
    option_id?: string | null;
}

export interface PingCommand extends ClientCommandBase {
    type: "ping";
}

/** Discriminated union of all client-to-server commands. */
export type ClientMessage =
    | SubscribeCommand
    | UnsubscribeCommand
    | SendMessageCommand
    | AgentControlCommand
    | PingCommand;

// Consumers that previously used components['schemas']['ServerEvent'] etc.
// should import these WS types directly as named exports from this module.
