"""Thread lifecycle management: reconciliation, recovery, dev-process registry."""

from .manager import (
    LifecycleError,
    ProcVerdict,
    attach,
    default_owner,
    endpoint_for,
    kill,
    list_verdicts,
    reap,
    rebuild,
    render_command,
    rerun,
    resolve,
    resume,
    spawn,
    tree_kill,
)
from .procs_config import (
    PortBand,
    ProcsConfig,
    ProcsConfigError,
    RoleConfig,
    load_procs_config,
    procs_config_path,
)
from .reconciliation import ReconciliationAction, compute_reconciliation_actions
from .registry import (
    ProcRecord,
    RegistryOwnershipError,
    StalenessState,
    allocate_port,
    classify_record,
    list_records,
    now_ms,
    procs_home,
    read_record,
    record_path,
    refresh_last_seen,
    remove_record,
    remove_record_if_owned,
    write_record,
)

__all__ = [
    "LifecycleError",
    "PortBand",
    "ProcRecord",
    "ProcVerdict",
    "ProcsConfig",
    "ProcsConfigError",
    "ReconciliationAction",
    "RegistryOwnershipError",
    "RoleConfig",
    "StalenessState",
    "allocate_port",
    "attach",
    "classify_record",
    "compute_reconciliation_actions",
    "default_owner",
    "endpoint_for",
    "kill",
    "list_records",
    "list_verdicts",
    "load_procs_config",
    "now_ms",
    "procs_config_path",
    "procs_home",
    "read_record",
    "reap",
    "rebuild",
    "record_path",
    "refresh_last_seen",
    "remove_record",
    "remove_record_if_owned",
    "render_command",
    "rerun",
    "resolve",
    "resume",
    "spawn",
    "tree_kill",
    "write_record",
]
